// !!! DO NOT EDIT THIS FILE - IT'S ONLY A CONVENCIENCE COPY OF CORRESPONDING *Shader.h FILE !!!

#version 410 core

// Ouput data
out vec4 color;

// Input data
in vec3 fragmentColor;

void main()
{
  // Output color
  color = vec4(fragmentColor,1.0f);
}
