// !!! DO NOT EDIT THIS FILE - IT'S ONLY A CONVENCIENCE COPY OF THE CORRESPONDING *Shader.h FILE !!!

#version 410 core

// Ouput data
out vec4 color;

// Input data
in vec4 fragmentColor;

void main()
{
  // Output color
  color = fragmentColor;

}
